### ISSUE TITLE
ADSI Return Value has Changed

### ISSUE THREAD

**Issue by Meatballs1** [darkoperator/Meterpreter-Scripts#3]
Upstream values from Extapi have changed which may break some of the enum_ad_ scripts... 

See: https://github.com/rapid7/metasploit-framework/pull/4389

Would also be cool if we can port them across at some point? I did an enum_ad_users to utilize the new Credentials structures but not as feature packed as yours:

https://github.com/rapid7/metasploit-framework/pull/4392

**Comment by darkoperator** [comment]
Fixed
